use std::time::{Duration, Instant};

pub struct State {
    pub exit: bool,
    pub menu: Menu,
    pub mode: Mode,
}

pub enum Menu {
    Home,
    Running,
    Done,
}

pub enum Mode {
    Clock {
        duration: Duration,
        start: Option<Instant>,
        target_words: Vec<String>,
        typed_words: Vec<String>,
    },
}

impl Default for State {
    fn default() -> Self {
        State {
            exit: false,
            menu: Menu::Home,
            mode: Mode::Clock {
                duration: Duration::from_secs(30),
                start: None,
                target_words: vec![
                    "lorem".to_string(),
                    "ipsum".to_string(),
                    "dolor".to_string(),
                    "sit".to_string(),
                    "amet".to_string(),
                    "consectetur".to_string(),
                    "adipiscing".to_string(),
                    "elit".to_string(),
                    "quisque".to_string(),
                    "faucibus".to_string(),
                    "ex".to_string(),
                    "sapien".to_string(),
                    "vitae".to_string(),
                    "pellentesque".to_string(),
                    "sem".to_string(),
                    "placerat".to_string(),
                    "in".to_string(),
                    "id".to_string(),
                    "cursus".to_string(),
                    "mi".to_string(),
                    "pretium".to_string(),
                    "tellus".to_string(),
                    "duis".to_string(),
                    "convallis".to_string(),
                    "tempus".to_string(),
                    "leo".to_string(),
                    "eu".to_string(),
                    "aenean".to_string(),
                    "sed".to_string(),
                    "diam".to_string(),
                    "urna".to_string(),
                    "tempor".to_string(),
                    "pulvinar".to_string(),
                    "vivamus".to_string(),
                    "fringilla".to_string(),
                    "lacus".to_string(),
                    "nec".to_string(),
                    "metus".to_string(),
                    "bibendum".to_string(),
                    "egestas".to_string(),
                    "iaculis".to_string(),
                    "massa".to_string(),
                    "nisl".to_string(),
                    "malesuada".to_string(),
                    "lacinia".to_string(),
                    "integer".to_string(),
                    "nunc".to_string(),
                    "posuere".to_string(),
                    "ut".to_string(),
                    "hendrerit".to_string(),
                    "semper".to_string(),
                    "vel".to_string(),
                    "class".to_string(),
                    "aptent".to_string(),
                    "taciti".to_string(),
                    "sociosqu".to_string(),
                    "ad".to_string(),
                    "litora".to_string(),
                    "torquent".to_string(),
                    "per".to_string(),
                    "conubia".to_string(),
                    "nostra".to_string(),
                    "inceptos".to_string(),
                    "himenaeos".to_string(),
                    "orci".to_string(),
                    "varius".to_string(),
                    "natoque".to_string(),
                    "penatibus".to_string(),
                    "et".to_string(),
                    "magnis".to_string(),
                    "dis".to_string(),
                    "parturient".to_string(),
                    "montes".to_string(),
                    "nascetur".to_string(),
                    "ridiculus".to_string(),
                    "mus".to_string(),
                    "donec".to_string(),
                    "rhoncus".to_string(),
                    "eros".to_string(),
                    "lobortis".to_string(),
                    "nulla".to_string(),
                    "molestie".to_string(),
                    "mattis".to_string(),
                    "scelerisque".to_string(),
                    "maximus".to_string(),
                    "eget".to_string(),
                    "fermentum".to_string(),
                    "odio".to_string(),
                    "phasellus".to_string(),
                    "non".to_string(),
                    "purus".to_string(),
                    "est".to_string(),
                    "efficitur".to_string(),
                    "laoreet".to_string(),
                    "mauris".to_string(),
                    "pharetra".to_string(),
                    "vestibulum".to_string(),
                    "fusce".to_string(),
                    "dictum".to_string(),
                    "risu".to_string(),
                ],
                typed_words: Vec::new(),
            },
        }
    }
}
